server:
  port: 9080    

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**
